# -*- coding: utf-8 -*-
from . import res_partner
from . import product_gi
from . import hr_employee
from . import hr_department
from . import product_category
from . import purchase_requisition
from . import purchase_requisition_line
from . import purchase_order_form
from . import cancel_purchase_requisition
from . import purchase_order_line
from . import boarding_ways
from . import purchase_consignee
from . import delivery_addresses
from . import account_invoice
from . import account_invoice_line
from . import stock_picking
from . import import_licenses
from . import input_free_wizard
from . import xml_no_validated
from . import res_users_gi
from . import purchase_reception
from . import use_cfdi
from . import stock_overprocessed_transfer
from . import purchase_immediate_transfer